# Generated by Django 3.1.2 on 2020-10-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email_admin', models.CharField(max_length=255)),
                ('password_admin', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('email_cliente', models.CharField(max_length=255)),
                ('password_cliente', models.CharField(max_length=30)),
                ('telefono_empresa', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
                ('servicio_activo', models.BooleanField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.FloatField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField()),
                ('detalles_contrato', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocsCliente',
            fields=[
                ('id_docs_cliente', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('doc_visita_mensual', models.BinaryField(blank=True, null=True)),
                ('doc_capacitacion', models.BinaryField(blank=True, null=True)),
                ('doc_asesoria', models.BinaryField(blank=True, null=True)),
                ('doc_resumen_mensual', models.BinaryField(blank=True, null=True)),
                ('doc_ficha_prevencion', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docs_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialProfesional',
            fields=[
                ('id_historial_prof', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('registro', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'historial_profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MultasCliente',
            fields=[
                ('id_multa', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'multas_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagosCliente',
            fields=[
                ('id_pago', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('pago', models.FloatField()),
            ],
            options={
                'db_table': 'pagos_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email_prof', models.EmailField(max_length=255)),
                ('password_prof', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_prof', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('contrato_activo', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=10)),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.FloatField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroError',
            fields=[
                ('id_reg_error', models.FloatField(primary_key=True, serialize=False)),
                ('sentencia_error', models.CharField(max_length=70)),
                ('mensaje_error', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registro_error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosExtraCliente',
            fields=[
                ('id_servicios_extra', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('visitas_extra', models.FloatField()),
                ('llamados_extra', models.FloatField()),
                ('capacitacion_extra', models.FloatField()),
                ('modif_lista_chequeo', models.FloatField()),
                ('actualizacion_docs', models.FloatField()),
            ],
            options={
                'db_table': 'servicios_extra_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tipo_cliente', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProfesional',
            fields=[
                ('id_tipo_profesional', models.FloatField(primary_key=True, serialize=False)),
                ('area_trabajo_profesional', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('nro_asesoria', models.FloatField()),
                ('hora_asesoria', models.DateField()),
                ('tipo_asesoria', models.CharField(max_length=50)),
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.servicio')),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('hora_cap', models.DateField()),
                ('asistentes', models.CharField(max_length=255)),
                ('materiales', models.CharField(max_length=100)),
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.servicio')),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('nivel_urgencia', models.CharField(max_length=50)),
                ('id_ticket', models.OneToOneField(db_column='id_ticket', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.ticket')),
                ('area', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emergencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('duracion', models.DateField()),
                ('id_ticket', models.OneToOneField(db_column='id_ticket', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.ticket')),
            ],
            options={
                'db_table': 'llamada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitaMensual',
            fields=[
                ('nro_visita', models.FloatField()),
                ('motivo', models.CharField(max_length=125)),
                ('lista_chequeo', models.BinaryField(blank=True, null=True)),
                ('nro_modif_lista_chequeo', models.FloatField()),
                ('ficha_prevencion', models.BinaryField(blank=True, null=True)),
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.servicio')),
            ],
            options={
                'db_table': 'visita_mensual',
                'managed': False,
            },
        ),
    ]
